-- MySQL Script generated by MySQL Workbench
-- Mon Jun 16 18:23:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cooperadora_escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cooperadora_escuela` ;

-- -----------------------------------------------------
-- Schema cooperadora_escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cooperadora_escuela` DEFAULT CHARACTER SET utf8 ;
USE `cooperadora_escuela` ;

-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`admin` (
  `idadmin` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`user` (
  `iduser` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_admin1_idx` (`admin_idadmin` ASC) VISIBLE,
  CONSTRAINT `fk_user_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `cooperadora_escuela`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`login` (
  `idlogin` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_login_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `cooperadora_escuela`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`productos` (
  `idproductos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_login1_idx` (`login_idlogin` ASC) VISIBLE,
  CONSTRAINT `fk_productos_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `cooperadora_escuela`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`compra` (
  `idcompra` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  PRIMARY KEY (`idcompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`carrito` (
  `idcarrito` INT NOT NULL,
  `realizar_compra` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `compra_idcompra` INT NOT NULL,
  PRIMARY KEY (`idcarrito`),
  INDEX `fk_carrito_compra1_idx` (`compra_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES `cooperadora_escuela`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperadora_escuela`.`prod_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperadora_escuela`.`prod_carrito` (
  `productos_idproductos` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  INDEX `fk_prod_carrito_productos1_idx` (`productos_idproductos` ASC) VISIBLE,
  PRIMARY KEY (`carrito_idcarrito`),
  CONSTRAINT `fk_prod_carrito_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `cooperadora_escuela`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prod_carrito_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `cooperadora_escuela`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
