# Generated by Django 5.1.5 on 2025-01-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
