# Generated by Django 5.1.5 on 2025-02-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0003_rename_imageurl_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperadora.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperadora.product')),
            ],
        ),
    ]
