# Generated by Django 5.1.5 on 2025-02-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0004_remove_order_products_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='cooperadora.OrderProduct', to='cooperadora.product'),
        ),
    ]
