# Generated by Django 5.1.5 on 2025-05-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0007_order_product_orderproduct_order_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('certificado', 'Certificado de estudiante Regular'), ('reincorporacion', 'Reincorporación'), ('mesa de examen', 'Mesa de Examen'), ('otro', 'Otro')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
